import { motion } from 'framer-motion';
import { Download, FileText, Code, Package, FileJson } from 'lucide-react';
import { Scene } from '../types';

export default function ExportPanel({
  scenes,
  storyIdea,
  artStyle,
  imageModel,
  videoModel,
}: {
  scenes: Scene[];
  storyIdea: string;
  artStyle: string;
  imageModel: string;
  videoModel: string;
}) {
  const exportOptions = [
    {
      label: 'Markdown Workflow',
      icon: FileText,
      desc: 'Readable workflow document',
      action: () => {
        const md = `# Storyboard Workflow: "${storyIdea || 'Untitled'}"\n\n## Settings\n- Style: ${artStyle}\n- Image Model: ${imageModel}\n- Video Model: ${videoModel}\n- Scenes: ${scenes.length}\n\n## Scenes\n${scenes.map((s, i) => `### Scene ${i + 1}\n- Description: ${s.description || 'N/A'}\n- Prompt: ${s.prompt?.slice(0, 100) || 'N/A'}...\n`).join('\n')}`;
        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `workflow-${Date.now()}.md`;
        a.click();
        URL.revokeObjectURL(url);
      },
    },
    {
      label: 'JSON Export',
      icon: FileJson,
      desc: 'Machine-readable data',
      action: () => {
        const data = { storyIdea, artStyle, imageModel, videoModel, scenes, exportedAt: new Date().toISOString() };
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `workflow-${Date.now()}.json`;
        a.click();
        URL.revokeObjectURL(url);
      },
    },
    {
      label: 'Prompt Pack',
      icon: Package,
      desc: 'All prompts in one file',
      action: () => {
        const prompts = scenes.map((s, i) => `Scene ${i + 1}: ${s.prompt}`).join('\n\n---\n\n');
        const blob = new Blob([prompts], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `prompts-${Date.now()}.txt`;
        a.click();
        URL.revokeObjectURL(url);
      },
    },
    {
      label: 'Production Brief',
      icon: Code,
      desc: 'Technical spec document',
      action: () => {
        const brief = [
          '# Production Brief',
          '',
          `## Project: ${storyIdea || 'Untitled'}`,
          `## Style: ${artStyle}`,
          `## Models: ${imageModel} → ${videoModel}`,
          `## Scenes: ${scenes.length}`,
          '',
          '### Scene Breakdown',
          ...scenes.map((s, i) => `Scene ${i + 1}: ${s.prompt?.slice(0, 80) || 'N/A'}`),
          '',
          '---',
          'Generated by Storyboard SaaS',
        ].join('\n');
        const blob = new Blob([brief], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `brief-${Date.now()}.md`;
        a.click();
        URL.revokeObjectURL(url);
      },
    },
  ];

  return (
    <div className="space-y-4">
      <div className="section-label">Export Options</div>
      <div className="grid grid-cols-2 gap-3">
        {exportOptions.map((opt) => (
          <motion.button
            key={opt.label}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={opt.action}
            className="glass-panel p-4 text-left hover:border-violet-500/30 transition-all group"
          >
            <opt.icon size={18} className="text-violet-400 mb-2 group-hover:text-violet-300 transition-colors" />
            <div className="text-sm font-medium text-white mb-0.5">{opt.label}</div>
            <div className="text-[10px] text-gray-500">{opt.desc}</div>
          </motion.button>
        ))}
      </div>

      {scenes.length > 0 && (
        <div className="glass-panel p-4 mt-4">
          <div className="section-label mb-3">Quality & Format</div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-xs text-gray-400 mb-1 block">Quality</label>
              <select className="select-field text-sm">
                <option>1080p</option>
                <option>4K Ultra HD</option>
                <option>720p</option>
              </select>
            </div>
            <div>
              <label className="text-xs text-gray-400 mb-1 block">Format</label>
              <select className="select-field text-sm">
                <option>MP4 (H.264)</option>
                <option>MOV</option>
                <option>WebM</option>
              </select>
            </div>
          </div>

          <button className="btn-primary w-full mt-4" onClick={() => alert('Export initiated! All assets ready for final render.')}>
            <Download size={15} /> Export Final Video
          </button>
        </div>
      )}
    </div>
  );
}